services:
  # SERVER
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "--configpath=/app/config.json",
        "--staticpath=/app/static",
        "--allowedorigins={*buttonmania.win,*buttonmania.top}",
        "--postgresurl=postgres://postgres:password@postgres:5432/buttonmania",
        "--redisaddress=redis:6379",
        # "--serverport=8080",
        "--serverport=443",
        "--servertlscert=/certs/buttonmania.pem",
        "--servertlskey=/certs/buttonmania.key",
        "--telegramdonateton=UQAaTJqQ4bqy6xxCUV-MSWMsJulwLAP1Dyma5TaA0aGwWiEe",
        "--telegramdonateeth=0x0948A61328b3eCeDa37CC33907F30d4AC06C34Ed",
        "--telegramdonatexmr=48D2unYK1NhfzQusXnXsU6ZrXfPxfSXrKPwTxEknwJygeC6wTSBkWorbX55EYZbBMHZLdeG1GXL8N9Xs6KSFCdEQ5xgoTqg",
      ]
    ports:
      - 8443:443
      - 8080:8080
    environment:
      - GIN_MODE=debug
      - TG_WEBHOOK_URL=${TG_WEBHOOK_URL}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN:?TG_BOT_TOKEN is required}
      - TG_APP_URL=${TG_APP_URL:?TG_APP_URL is required}
    volumes:
      - ./certs/buttonmania.key:/certs/buttonmania.key:ro
      - ./certs/buttonmania.pem:/certs/buttonmania.pem:ro
    networks:
      - buttonmania-network
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"
  # POSTGRES
  postgres:
    image: postgres:alpine
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=buttonmania
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - buttonmania-network
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  # REDIS
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - buttonmania-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
networks:
  buttonmania-network:
volumes:
  redis-data:
  postgres-data:
