version: "3.8"
services:
  # SERVER
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "--staticpath=/app/static",
        "--allowedorigins={*buttonmania.win,*buttonmania.top}",
        "--redisaddress=redis:6379",
        "--telegramdonateton=UQAaTJqQ4bqy6xxCUV-MSWMsJulwLAP1Dyma5TaA0aGwWiEe",
        "--telegramdonateeth=0x0948A61328b3eCeDa37CC33907F30d4AC06C34Ed",
        "--telegramdonatexmr=48D2unYK1NhfzQusXnXsU6ZrXfPxfSXrKPwTxEknwJygeC6wTSBkWorbX55EYZbBMHZLdeG1GXL8N9Xs6KSFCdEQ5xgoTqg"
      ]
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=debug
      - TG_BOT_TOKEN=${TG_BOT_TOKEN:?TG_BOT_TOKEN is required}
      - TG_APP_URL=${TG_APP_URL:?TG_APP_URL is required}
    networks:
      - buttonmania-network
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"
  # REDIS
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - buttonmania-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
networks:
  buttonmania-network:
volumes:
  redis-data:
